### ISSUE TITLE
Implement: Validation in form elements

### ISSUE THREAD

**Issue by jayantkandpal** [11WALTER11/Certify#10]
Validation in form(appreciation and participation)

Issue:
Blank certificate is downloaded when user clicks on 'Download Certificate' without entering any details

Expected:
Validation for each field in form.

**Comment by 11WALTER11** [comment]
Hi @jayantkandpal,

Go ahead  🚀!

**Comment by jayantkandpal** [comment]
@11WALTER11 Changes done. Validation alert implemented and have opened PR for the same.
