### ISSUE TITLE
Migrate: CRA to VITE

### ISSUE THREAD

**Issue by 11WALTER11** [11WALTER11/Certify#11]
Follow this article for help : https://cathalmacdonnacha.com/migrating-from-create-react-app-cra-to-vite

**Comment by rahmlad-aramide** [comment]
Hi @11WALTER11 
Kindly assign this task to me, I'll like to take it up
Thank you

**Comment by 11WALTER11** [comment]
@rahmlad-aramide go ahead 🚀

**Comment by rahmlad-aramide** [comment]
Thank you for assigning it to me, I'm on it.
@11WALTER11

**Comment by rahmlad-aramide** [comment]
@11WALTER11 hope you can see my pull request? I can see that it's still lying there waiting for your approval, kindly review as appropriate, thank you
